package com.moviebookingsystem.app.models;

import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

@Getter
@Setter
@MappedSuperclass
public abstract class Exposed extends Auditable {

    private UUID exposedId; // autogenerated at the time of object creation
    // place an index on this
}
